services:
  - type: web
    name: ArguLex
    env: python
    region: oregon            # Change if you want a different region
    branch: main              # Your GitHub branch name
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGODB_URI
        fromSecret: MONGODB_URI_SECRET
        sync: false
      - key: SECRET_KEY
        fromSecret: SECRET_KEY_SECRET
        sync: false
      - key: DEBUG
        value: "False"
        sync: false
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY_SECRET
        sync: false
        
